### ISSUE TITLE
Configurable message-ttl

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq#10]
1. On a queue level for transformer, db, and history.  configurable in the general db. This stays in the manager, client doesn't need to know about this
2. Configurable to the sources, this makes it independent of the queues,  but it involves running code on the clients. It may also be less efficient than setting per-queue.

**Comment by tilsche** [comment]
Addressed in https://github.com/metricq/metricq-manager/commit/c814eb54369d1b5977c9b9b3abf306816557d2bb
but only 1) transformer. The rest remains a todo

**Comment by bmario** [comment]
Fixed in metricq/metricq-manager#9
