### ISSUE TITLE
History vHost required?

### ISSUE THREAD

**Issue by bmario** [metricq/metricq#18]
I'm working on a history client in the C++ part and noticed that the db isn't using the historyDataAddress. 

Thoughts:
- if we want the additional vHost, db needs to be adapted and we need to replicate the code of the data_client class with s/data/history

**Comment by bmario** [comment]
745b735644518aaae9dcc1cfec0b9f96504c6f88 removed the history vHost

**Comment by tilsche** [comment]
https://github.com/metricq/metricq-manager/commit/b59eaedf7ed6e6931f4b8ac7c816ddee4aa23c69 changes this in the manager. For now the `historyServerAddress` is still provided for compatibility.
