### ISSUE TITLE
Use immediate confirms to determine un-routed history requests

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq#27]
This change gives history clients fast and easy feedback if any currently available DBs stores a specific metric and thus can provide historical data for the given metric.

**Comment by kinnarr** [comment]
Use immediate flag for publish command (https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.publish)

**Comment by kinnarr** [comment]
The flag was removed 😒 
https://www.rabbitmq.com/blog/2012/11/19/breaking-things-with-rabbitmq-3-0/

**Comment by bmario** [comment]
So in summary, this is not possible to fix.
