### ISSUE TITLE
 Handle connection issues properly

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq#3]
For the case of missed heartbeats, the connection ends up in a weird state where [non-ssl: nothing happens any more, ssl: weird error, _socket == -1 during assign for new watcher]. We also cannot shut this down correctly in the sigint handler at the moment.

This should be handled more gracefully. We observed this with metricq-db-hta but this is probably a general thing.

**Comment by tilsche** [comment]
Editing the issue for wider context:

1. Heartbeat disconnect
2. Server-side connection close (probably different than 1.)
3. Ensure not only reconnect, but also functioning channels and queues

This affects both python and C++.

**Comment by tilsche** [comment]
An alternative for trying to get the automatic reconnect working properly is to cleanly shut down a client such that it can be restarted by systemd and go through the normmal connect/register procedure.

**Comment by tilsche** [comment]
Wit the update of aio_pika this seems to work now. Tested locally with `metricq_synchronous_source.py` and ssl.

**Comment by bmario** [comment]
The c++ interface implementation no reliably shuts down on connection errors. There haven't been seen any weird issues in the wild lastly, so I'm going to close this issue.
