### ISSUE TITLE
Agree on discover RPC response structure

### ISSUE THREAD

**Issue by phijor** [metricq/metricq#55]
Right now, all three of the C++ client code, the Python interface and the Wiki disagree on how to properly respond to a `discover` RPC:

C++:
https://github.com/metricq/metricq/blob/9ec1a7ff4f63ab5dcf527f551d3efda14d6e26fd/src/data_client.cpp#L43-L49

Python:
https://github.com/metricq/metricq/blob/9ec1a7ff4f63ab5dcf527f551d3efda14d6e26fd/python/metricq/client.py#L88-L96

The Wiki:
* `alive`: `bool`
* `current_time`: ISO date
* `starting_time`: ISO date

The way we do it in Python is my personal favorite, but what should be the way forward?

**Comment by tilsche** [comment]
Well, the wiki contradicts itself:

> Command parameters and return in JSON are in `lowerCamelCase`.

How about

- `alive` bool (optional) assume true if omitted
- `startingTime` ISO 8601 date string (optional) datetime the source was last started
- `currentTime` ISO 8601 date string (optional) current datetime of the source
- `uptime` number in nanoseconds (optional) computed from `currentTime` and `startingTime` if given

**Comment by phijor** [comment]
Having these four fields with sensible defaults sounds good. I'm not quite happy with calling it `startingTime` though, in my mind it should be something like `startTime` or `startupTime`. But that's not too important.

**Comment by tilsche** [comment]
I agree the naming is a bit wonky. But I don't think we should change at this point without very clear reason. Can you make the necessary changes in a PR?
