### ISSUE TITLE
Improve Cluster configuration for more resilience

### ISSUE THREAD

**Issue by bmario** [metricq/metricq#63]

**Comment by tilsche** [comment]
The main issue seem to be queues that live only on one node. When that node goes down, things go bad. Therefore we should try to find out how queues can be configured / controlled to be:
 - Resilient to planned shutdowns of individual nodes
 - Data may even be lost if need be, but it should be possible to continue using the queue while the nodes are down.
 - (Aggregate) throughput performance should not be limited by this
 - Latency may be impacted

Currently we are looking at quorum queues.
